### ISSUE TITLE
ionic-script3.1.2  angular 5.0.1 when --prod Field 'browser' doesn't contain a valid alias configuration 

### ISSUE THREAD

**Issue by adongroom** [ionic-team/ionic-app-scripts#1326]
ionic-app-script task: "build"
[15:06:00]  Error: ./src/app/main.ts Module not found: Error: Can't resolve './app.module.ngfactory' in
            '/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app' resolve './app.module.ngfactory' in
            '/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app' using description file:
            /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/package.json (relative path: ./src/app) Field
            'browser' doesn't contain a valid alias configuration after using description file:
            /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/package.json (relative path: ./src/app) using
            description file: /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/package.json (relative path:
            ./src/app/app.module.ngfactory) no extension Field 'browser' doesn't contain a valid alias configuration
            /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory doesn't exist .ts
            Field 'browser' doesn't contain a valid alias configuration
            /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.ts doesn't exist .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.js doesn't exist
            .json Field 'browser' doesn't contain a valid alias configuration
            /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.json doesn't exist
            as directory /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory doesn't
            exist [/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory]
            [/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.ts]
            [/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.js]
            [/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.json]
            [/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory] @
            ./src/app/main.ts 2:0-60
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app'
resolve './app.module.ngfactory' in '/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app'
  using description file: /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/package.json (relative path: ./src/app)
    using description file: /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.json doesn't exist
      as directory
        /Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory doesn't exist
[/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory]
[/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.ts]
[/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.js]
[/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory.json]
[/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/src/app/app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at new BuildError (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/hanzhendong/workspace/web/angular-webapp/qingjianew/node_modules/webpack/lib/Compiler.js:365:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qingjianew@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qingjianew@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hanzhendong/.npm/_logs/2017-11-26T07_06_00_848Z-debug.log
➜  qingjianew git:(master)

**Comment by danbucholtz** [comment]
This is fixed in `3.1.4`.

Thanks,
Dan

**Comment by jbrueggmann** [comment]
Is there anything else that has to be updated?
I updated @ionic/app-scripts to 3.1.4 but the issue remains for me


$ npm ls @ionic/app-scripts
xxx@0.0.1 /Users/foobar/git/foo/bar/app
└── @ionic/app-scripts@3.1.4




Module not found: Error: Can't resolve '@app/env' in '/Users/foobar/git/foo/bar/app/src/providers/bar'
resolve '@app/env' in '/Users/foobar/git/foo/bar/app/src/providers/bar'
  Parsed request is a module
  using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./src/providers/bar)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./src/providers/bar)
    resolve as module
      looking for modules in /Users/foobar/git/foo/bar/app/node_modules
        using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./node_modules)
          using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./node_modules/@app/env)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env.json doesn't exist
            as directory
              /Users/foobar/git/foo/bar/app/node_modules/@app/env doesn't exist
[/Users/foobar/git/foo/bar/app/node_modules/@app/env]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env.ts]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env.js]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env.json]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env]
 @ ./src/providers/bar/bar.provider.ts 5:0-31
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./src/providers/authentication/authentication.provider.ts
Module not found: Error: Can't resolve '@app/env' in '/Users/foobar/git/foo/bar/app/src/providers/authentication'
resolve '@app/env' in '/Users/foobar/git/foo/bar/app/src/providers/authentication'
  Parsed request is a module
  using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./src/providers/authentication)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./src/providers/authentication)
    resolve as module
      looking for modules in /Users/foobar/git/foo/bar/app/node_modules
        using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./node_modules)
          using description file: /Users/foobar/git/foo/bar/app/package.json (relative path: ./node_modules/@app/env)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/foobar/git/foo/bar/app/node_modules/@app/env.json doesn't exist
            as directory
              /Users/foobar/git/foo/bar/app/node_modules/@app/env doesn't exist
[/Users/foobar/git/foo/bar/app/node_modules/@app/env]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env.ts]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env.js]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env.json]
[/Users/foobar/git/foo/bar/app/node_modules/@app/env]
 @ ./src/providers/authentication/authentication.provider.ts 7:0-31
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (/Users/foobar/git/foo/bar/app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/foobar/git/foo/bar/app/node_modules/@ionic/app-scripts/dist/webpack.js:121:28)
    at emitRecords.err (/Users/foobar/git/foo/bar/app/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/foobar/git/foo/bar/app/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/foobar/git/foo/bar/app/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/foobar/git/foo/bar/app/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/foobar/git/foo/bar/app/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/foobar/git/foo/bar/app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/foobar/git/foo/bar/app/node_modules/tapable/lib/Tapable.js:222:13)
