### ISSUE TITLE
Duplicate css after Sass task

### ISSUE THREAD

**Issue by markisme** [ionic-team/ionic-app-scripts#388]
Every time, after run ionic serve, i get duplicate css definition in main.css, then i try to find why and find that after sass task, the duplicate css appeared. Does anyone know the reason and how can i fix it?

and i'm using @ionic/app-scripts 0.0.43.

**Comment by markisme** [comment]
![image](https://cloud.githubusercontent.com/assets/7677941/20259285/11cebcd2-aa8f-11e6-82f1-e8274477ac6e.png)

**Comment by alan-agius4** [comment]
Are you using `@extends`?

**Comment by markisme** [comment]
```
.toolbar{
        text-align: center;
        .logo{
            display: inline-block;
            height: 40px;
            margin-left: 30px;
        }
        .search{
            color: $primary;
        }
        /*.activated{
        border-width: 2px;
        border-style: grayscale($color: $dark);
        border-color: buttonface;
        }*/
    }
```
@alan-agius4 that's the .toolbar in home.scss

**Comment by markisme** [comment]
And now i find that there are also duplicate code in main.js. Just i have this problem??

**Comment by ataraxus** [comment]
I also noticed duplicated css, but didn't drill down where this comes from

**Comment by danbucholtz** [comment]
I believe this is resolved in `1.0.0`. Please let me know if it's not.

Thanks,
Dan

**Comment by markisme** [comment]
@danbucholtz still not solved,I think.
![image](https://cloud.githubusercontent.com/assets/7677941/24286768/9d734464-10b1-11e7-8076-1aa63b345f7b.png)
And the `ionic info`:
Your system information:
```
Cordova CLI: 6.5.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.10.1
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by markisme** [comment]
@danbucholtz did i need reopen an issue?

**Comment by Grohden** [comment]
Same here
![ionic bug](https://cloud.githubusercontent.com/assets/7496871/25616672/8c4b45c0-2f14-11e7-84c3-6d345d744fa5.png)

```
Cordova CLI: 6.5.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed
```

Maybe is a bug on chrome (notice the blank stylesheet name)? I could not make the live reload work on firefox (it just doesn't reload) :/

**Comment by Grohden** [comment]
Forgot to comment my 'solution' here, i was importing the same stylesheet twice, when i removed one of the imports it fixed the problem.

**Comment by judsonmusic** [comment]
I am having the same issue came someone explain in detail how to resolve?

**Comment by danbucholtz** [comment]
I think this is user error. I cannot recreate.

Thanks,
Dan
